run:
  timeout: "10m"
  concurrency: 10

linters-settings:
  exhaustive:
    default-signifies-exhaustive: true

  revive:
    ignore-generated-header: false
    severity: "warning"
    confidence: 3

  depguard:
    rules:
      main:
        allow: [] # allow all
        deny:
          - pkg: "io/ioutil"
            desc: "Deprecated: As of Go 1.16, the same functionality is now provided by package io or package os, and those implementations should be preferred in new code. See the specific details in the Go documentation."
          - pkg: "gopkg.in/yaml.v2"
            desc: "Grafana packages are not allowed to depend on gopkg.in/yaml.v2 as gopkg.in/yaml.v3 is now available"
          - pkg: "github.com/pkg/errors"
            desc: "Deprecated: Go 1.13 supports the functionality provided by pkg/errors in the standard library."
          - pkg: "github.com/xorcare/pointer"
            desc: "Use pkg/util.Pointer instead, which is a generic one-liner alternative"
          - pkg: "github.com/gofrs/uuid"
            desc: "Use github.com/google/uuid instead, which we already depend on."
          - pkg: "github.com/bmizerany/assert"
            desc: "Use github.com/stretchr/testify/assert instead, which we already depend on."

      coreplugins:
        deny:
          - pkg: "github.com/grafana/grafana/pkg/api"
            desc: "Core plugins are not allowed to depend on Grafana core packages"
          - pkg: "github.com/grafana/grafana/pkg/cmd"
            desc: "Core plugins are not allowed to depend on Grafana core packages"
          - pkg: "github.com/grafana/grafana/pkg/cuectx"
            desc: "Core plugins are not allowed to depend on Grafana core packages"
          - pkg: "github.com/grafana/grafana/pkg/extensions"
            desc: "Core plugins are not allowed to depend on Grafana core packages"
          - pkg: "github.com/grafana/grafana/pkg/kinds"
            desc: "Core plugins are not allowed to depend on Grafana core packages"
          - pkg: "github.com/grafana/grafana/pkg/middleware"
            desc: "Core plugins are not allowed to depend on Grafana core packages"
          - pkg: "github.com/grafana/grafana/pkg/modules"
            desc: "Core plugins are not allowed to depend on Grafana core packages"
          - pkg: "github.com/grafana/grafana/pkg/registry"
            desc: "Core plugins are not allowed to depend on Grafana core packages"
          - pkg: "github.com/grafana/grafana/pkg/services"
            desc: "Core plugins are not allowed to depend on Grafana core packages"
          - pkg: "github.com/grafana/grafana/pkg/build"
            desc: "Core plugins are not allowed to depend on Grafana core packages"
          - pkg: "github.com/grafana/grafana/pkg/codegen"
            desc: "Core plugins are not allowed to depend on Grafana core packages"
          - pkg: "github.com/grafana/grafana/pkg/events"
            desc: "Core plugins are not allowed to depend on Grafana core packages"
          - pkg: "github.com/grafana/grafana/pkg/ifaces"
            desc: "Core plugins are not allowed to depend on Grafana core packages"
          - pkg: "github.com/grafana/grafana/pkg/kindsysreport"
            desc: "Core plugins are not allowed to depend on Grafana core packages"
          - pkg: "github.com/grafana/grafana/pkg/mocks"
            desc: "Core plugins are not allowed to depend on Grafana core packages"
          - pkg: "github.com/grafana/grafana/pkg/plugins"
            desc: "Core plugins are not allowed to depend on Grafana core packages"
          - pkg: "github.com/grafana/grafana/pkg/setting"
            desc: "Core plugins are not allowed to depend on Grafana core packages"
          - pkg: "github.com/grafana/grafana/pkg/util"
            desc: "Core plugins are not allowed to depend on Grafana core packages"
          - pkg: "github.com/grafana/grafana/pkg/bus"
            desc: "Core plugins are not allowed to depend on Grafana core packages"
          - pkg: "github.com/grafana/grafana/pkg/components"
            desc: "Core plugins are not allowed to depend on Grafana core packages"
          - pkg: "github.com/grafana/grafana/pkg/expr"
            desc: "Core plugins are not allowed to depend on Grafana core packages"
          - pkg: "github.com/grafana/grafana/pkg/infra"
            desc: "Core plugins are not allowed to depend on Grafana core packages"
          - pkg: "github.com/grafana/grafana/pkg/login"
            desc: "Core plugins are not allowed to depend on Grafana core packages"
          - pkg: "github.com/grafana/grafana/pkg/models"
            desc: "Core plugins are not allowed to depend on Grafana core packages"
          - pkg: "github.com/grafana/grafana/pkg/server"
            desc: "Core plugins are not allowed to depend on Grafana core packages"
          - pkg: "github.com/grafana/grafana/pkg/tests"
            desc: "Core plugins are not allowed to depend on Grafana core packages"
          - pkg: "github.com/grafana/grafana/pkg/web"
            desc: "Core plugins are not allowed to depend on Grafana core packages"
          - pkg: "github.com/grafana/grafana/pkg/tsdb/intervalv2"
            desc: "Core plugins are not allowed to depend on Grafana core packages"
        files:
          - "**/pkg/tsdb/grafana-pyroscope-datasource/*"
          - "**/pkg/tsdb/grafana-pyroscope-datasource/**/*"
          - "**/pkg/tsdb/grafana-testdata-datasource/*"
          - "**/pkg/tsdb/grafana-testdata-datasource/**/*"
          - "**/pkg/tsdb/azuremonitor/*"
          - "**/pkg/tsdb/azuremonitor/**/*"
          - "**/pkg/tsdb/cloud-monitoring/*"
          - "**/pkg/tsdb/cloud-monitoring/**/*"
          - "**/pkg/tsdb/mysql/*"
          - "**/pkg/tsdb/mysql/**/*"
          - "**/pkg/tsdb/parca/*"
          - "**/pkg/tsdb/parca/**/*"
          - "**/pkg/tsdb/tempo/*"
          - "**/pkg/tsdb/tempo/**/*"
          - "**/pkg/tsdb/cloudwatch/*"
          - "**/pkg/tsdb/cloudwatch/**/*"

      apiserver:
        list-mode: "lax"
        allow:
          - "github.com/grafana/grafana/pkg/apimachinery"
          - "github.com/grafana/grafana/pkg/apiserver"
          - "github.com/grafana/grafana/pkg/services/apiserver/utils"
          - "github.com/grafana/grafana/pkg/services/featuremgmt"
          - "github.com/grafana/grafana/pkg/infra/kvstore"
          - "github.com/grafana/grafana/pkg/services/apiserver/options"
          - "github.com/grafana/grafana/pkg/apis/playlist/v0alpha1"
        deny:
          - pkg: "github.com/grafana/grafana/pkg"
            desc: "apiserver is not allowed to import grafana core"
        files:
          - "**/pkg/apiserver/*"
          - "**/pkg/apiserver/**/*"

      apimachinery:
        list-mode: "lax"
        allow:
          - "github.com/grafana/grafana/pkg/apimachinery"
        deny:
          - pkg: "github.com/grafana/grafana/pkg"
            desc: "apimachinery is not allowed to import grafana core"
        files:
          - "**/pkg/apimachinery/*"
          - "**/pkg/apimachinery/**/*"

      promlib:
        list-mode: "lax" # allow unless explicitly denied
        allow:
          - "github.com/grafana/grafana/pkg/promlib"
        deny:
          - pkg: "github.com/grafana/grafana/pkg"
            desc: "promlib is not allowed to import grafana core"
        files:
          - "**/pkg/promlib/*"
          - "**/pkg/promlib/**/*"

  gocritic:
    enabled-checks: ["ruleguard"]
    settings:
      ruleguard:
        rules: "pkg/ruleguard.rules.go"

  misspell:
    ignore-words: ["Unknwon", "Creater"]

  nakedret:
    max-func-lines: 60

linters:
  disable-all: true
  enable:
    - "bodyclose"
    - "depguard"
    - "dogsled"
    - "errcheck"
    # "gochecknoinits",
    # "goconst",
    # "gocritic" # Temporarily disabled on 2022-09-09, running into weird bug "ruleguard: execution error: used Run() with an empty rule set; forgot to call Load() first?"
    - "goimports"
    - "goprintffuncname"
    - "gosec"
    - "gosimple"
    - "govet"
    - "ineffassign"
    - "misspell"
    - "nakedret"
    - "exportloopref"
    - "staticcheck"
    - "stylecheck"
    - "typecheck"
    - "unconvert"
    - "unused"
    - "whitespace"
    - "gocyclo"
    - "exhaustive"
    - "typecheck"
    - "asciicheck"
    - "errorlint"
    - "revive"

issues:
  exclude-use-default: false
  max-same-issues: 0
  exclude-dirs:
    - devenv
    - scripts
  exclude-rules:
    - linters: ["stylecheck"]
      text: "ST1003"
    - linters: ["stylecheck"]
      text: "ST1001"
    - linters: ["staticcheck"]
      text: "SA1019: http.CloseNotifier"
    - linters: ["staticcheck"]
      text: "SA1019: strings.Title"
    - linters: ["staticcheck"]
      text: "SA1019: \"go.opentelemetry.io/otel/exporters/jaeger\""
    - linters: ["staticcheck"]
      text: "use fake service and real access control evaluator instead"
    - linters: ["gosec"]
      text: "G108"
    - linters: ["gosec"]
      text: "G110"
    - linters: ["gosec"]
      text: "G201"
    - linters: ["gosec"]
      text: "G202"
    - linters: ["gosec"]
      text: "G306"
    - linters: ["gosec"]
      text: "401"
    - linters: ["gosec"]
      text: "402"
    - linters: ["gosec"]
      text: "501"
    - linters: ["gosec"]
      text: "404"
    - linters: ["errorlint"]
      text: "non-wrapping format verb for fmt.Errorf"
    # TODO: Enable
    - linters: ["stylecheck"]
      text: "ST1000"
    # TODO: Enable
    - linters: ["stylecheck"]
      text: "ST1020"
    # TODO: Enable
    - linters: ["stylecheck"]
      text: "ST1021"
    - linters: ["gosec"]
      path: "(.+)_test\\.go"
      text: "G601"
    - linters: ["gosec"]
      text: G115
