name: 'Run Backend Tests'
description: 'Runs Grafana backend test suites'

inputs:
  test-command:
    description: 'The test command to run'
    required: true

runs:
  using: "composite"
  steps:
    - name: Generate Go files
      shell: bash
      run: make gen-go

    - name: Run tests
      shell: bash
      run: ${{ inputs.test-command }}
