name: 'Run Backend Tests'
description: 'Runs the Grafana backend unit tests with code generation'

runs:
  using: "composite"
  steps:
    - name: Run tests with code generation
      shell: bash
      run: make gen-go test-go-unit
