name: 'Determine Edition'
description: 'Determines whether to use OSS or Enterprise edition and sets environment variables'
outputs:
  edition:
    description: 'The edition to use (oss or enterprise)'
    value: ${{ steps.set-edition.outputs.edition }}
  use_enterprise:
    description: 'Whether to use enterprise features'
    value: ${{ steps.set-edition.outputs.use_enterprise }}
runs:
  using: "composite"
  steps:
    - name: Set edition based on repository type
      id: set-edition
      shell: bash
      run: |
        if [[ "${{ github.event_name }}" == "pull_request" && "${{ github.event.pull_request.head.repo.fork }}" == "false" ]]; then
          echo "edition=enterprise" >> $GITHUB_OUTPUT
          echo "use_enterprise=true" >> $GITHUB_OUTPUT
          echo "Using enterprise edition"
          
          # Set environment variables for all subsequent steps
          echo "EDITION=enterprise" >> $GITHUB_ENV
          echo "WIRE_TAGS=enterprise" >> $GITHUB_ENV
          echo "GO_TAGS=enterprise" >> $GITHUB_ENV
          
          # Create a file that can be checked for edition status
          mkdir -p $GITHUB_WORKSPACE/.github/workflow-state
          echo "enterprise" > $GITHUB_WORKSPACE/.github/workflow-state/edition
        else
          echo "edition=oss" >> $GITHUB_OUTPUT
          echo "use_enterprise=false" >> $GITHUB_OUTPUT
          echo "Using OSS edition"
          
          # Set environment variables for all subsequent steps
          echo "EDITION=oss" >> $GITHUB_ENV
          echo "WIRE_TAGS=oss" >> $GITHUB_ENV
          echo "GO_TAGS=oss" >> $GITHUB_ENV
          
          # Create a file that can be checked for edition status
          mkdir -p $GITHUB_WORKSPACE/.github/workflow-state
          echo "oss" > $GITHUB_WORKSPACE/.github/workflow-state/edition
        fi
