name: grafana-fs-dev

services:
  reverse-proxy:
    image: fs-reverse-proxy
    build:
      context: .
      dockerfile: nginx.dockerfile
    volumes:
      - ./public/build:/usr/share/nginx/html/public/build
      - ./public/fonts:/usr/share/nginx/html/public/fonts
    ports:
      - '3000:80' # Gateway
      - '3010:81' # CDN

  backend:
    image: grafana-backend
    build:
      context: .
      dockerfile: tilt-backend-base.dockerfile
    entrypoint: ['bin/grafana', 'server']
    volumes:
      - backend-data:/grafana/data
    environment:
      GF_FEATURE_TOGGLES_ENABLE: multiTenantFrontend
      GF_SERVER_CDN_URL: http://host.docker.internal:3010
      GF_PLUGINS_CDN_BASE_URL: 'https://plugins-cdn.grafana.net'
    ports:
      - '3011:3000'

  frontend-service:
    image: grafana-backend
    build:
      context: .
      dockerfile: tilt-backend-base.dockerfile
    entrypoint: ['bin/grafana', 'server', 'target']
    ports:
      - '3012:3000'
    environment:
      GF_DEFAULT_APP_MODE: development
      GF_DEFAULT_TARGET: frontend-server
      GF_SECURITY_CONTENT_SECURITY_POLICY: false
      GF_SERVER_CDN_URL: http://host.docker.internal:3010

volumes:
  backend-data:
