---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: folder-user
rules:
  - apiGroups:
      - folder.grafana.app
    resources:
      - folders
      - folders/status
    verbs:
      - create
      - update
      - patch
      - delete
      - deletecollection
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: folder-lister
rules:
  - apiGroups:
      - folder.grafana.app
    resources:
      - folders
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: operator:folder-user-rolebinding
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: folder-user
subjects:
  - kind: ServiceAccount
    name: operator
    namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: grafana:folder-user-rolebinding
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: folder-user
subjects:
  - kind: ServiceAccount
    name: grafana
    namespace: default
