name: Start Grafana server
description: Starts a Grafana server for use with e2e tests

inputs:
  package:
    description: A Grafana tar.gz package
    required: true

runs:
  using: composite
  steps:
    - shell: bash
      run: |
        mkdir -p workspace/grafana
        tar --strip-components=1 -xvf ${{ inputs.package }} -C ./workspace/grafana
    - shell: bash
      run: cp -r devenv scripts tools ./workspace/grafana
    - shell: bash
      env:
        GF_APP_MODE: development
        GF_SERVER_HTTP_PORT: "3001"
        GF_SERVER_ROUTER_LOGGING: "1"
      run: |
        pushd ./workspace/grafana
        ./scripts/grafana-server/start-server &
        popd
    - shell: bash
      run: curl --retry 20 --retry-delay 1 --retry-all-errors http://localhost:3001
