name: 'Run Backend Integration Tests'
description: 'Runs the Grafana backend integration tests'

runs:
  using: "composite"
  steps:
    - name: Run integration tests
      shell: bash
      run: make test-go-integration
