name: 'Setup Common Backend Testing Environment'
description: 'Sets up common environment variables and configurations for backend testing'

outputs:
  edition:
    description: 'Edition to use (enterprise or oss)'
    value: ${{ steps.set-env.outputs.edition }}
  wire-tags:
    description: 'Wire tags to use'
    value: ${{ steps.set-env.outputs.wire_tags }}

runs:
  using: "composite"
  steps:
    - id: set-env
      shell: bash
      run: |
        if [[ "${{ github.event_name }}" == "pull_request" && "${{ github.event.pull_request.head.repo.fork }}" == "false" ]]; then
          echo "edition=enterprise" >> $GITHUB_OUTPUT
          echo "wire_tags=enterprise" >> $GITHUB_OUTPUT
        else
          echo "edition=oss" >> $GITHUB_OUTPUT
          echo "wire_tags=oss" >> $GITHUB_OUTPUT
        fi
