name: Backend Coverage
on:
  push:
    paths:
      - pkg/**
      - .github/workflows/backend-coverage.yml
      - go.*
    branches:
      - main
  pull_request:

jobs:
  coverage:
    runs-on: ubuntu-latest
    if: github.repository == 'grafana/grafana'
    steps:
      - name: Check out repository
        uses: actions/checkout@v4.2.2
      - name: Setup Go environment
        uses: actions/setup-go@v5.3.0
        with:
          go-version-file: go.work
      - name: Run tests
        run: make gen-go test-go
      - name: Generate coverage info
        run: make test-go-cover
      - name: Convert coverage info to per-func stats
        run: go tool cover -func backend.cov > /tmp/backend-funcs.log
      - name: Upload coverage file
        uses: actions/upload-artifact@v4
        with:
          name: backend-cov
          path: |
            backend.cov
            /tmp/backend-funcs.log
          retention-days: 30 # this is a pretty small file; 10MB or so. it is GZip compressed by the action, which makes it <1MB.
          compression-level: 9 # this is raw text, and includes a _lot_ of repetition. compressing it should yield pretty good results.
      - name: Set summary to total coverage
        run:
          echo "# Coverage" >> $GITHUB_STEP_SUMMARY
          echo "```" >> $GITHUB_STEP_SUMMARY
          grep 'total:' /tmp/backend-funcs.log >> $GITHUB_STEP_SUMMARY
          echo "```" >> $GITHUB_STEP_SUMMARY