name: Create community release post
on:
  workflow_call:
    inputs:
      version:
        type: string
        required: true
        description: 'Needs to match, exactly, the name of a milestone. The version to be released please respect: major.minor.patch, major.minor.patch-preview or major.minor.patch-preview<number> format. example: 7.4.3, 7.4.3-preview or 7.4.3-preview1'
      dry_run:
        type: bool
        required: false
        default: false
        description: When enabled, this workflow will print a preview instead of creating an actual post.
  workflow_dispatch:
    inputs:
      version:
        type: string
        required: true
        description: 'Needs to match, exactly, the name of a milestone. The version to be released please respect: major.minor.patch, major.minor.patch-preview or major.minor.patch-preview<number> format. example: 7.4.3, 7.4.3-preview or 7.4.3-preview1'
      dry_run:
        type: bool
        required: false
        default: false
        description: When enabled, this workflow will print a preview instead of creating an actual post.
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: "Generate token"
        id: generate_token
        uses: tibdex/github-app-token@b62528385c34dbc9f38e5f4225ac829252d1ea92
        with:
          app_id: ${{ secrets.GRAFANA_DELIVERY_BOT_APP_ID }}
          private_key: ${{ secrets.GRAFANA_DELIVERY_BOT_APP_PEM }}
      - name: Run community-release (manually invoked)
        uses: grafana/grafana-github-actions-go/community-release@main
        with:
          token: ${{ steps.generate_token.outputs.token }}
          version: ${{ inputs.version }}
          metrics_api_key: ${{ secrets.GRAFANA_MISC_STATS_API_KEY }}
          community_api_key: ${{ secrets.GRAFANABOT_FORUM_KEY }}
          community_api_username: grafanabot
          dry_run: ${{ inputs.dry_run }}
