name: Create next release branch
on:
  workflow_call:
    inputs:
      source:
        description: The release branch to increment (eg providing `release-11.2.3` will result in `release-11.2.4` being created)
        type: string
        required: true
  workflow_dispatch:
    inputs:
      source:
        description: The release branch to increment (eg providing `release-11.2.3` will result in `release-11.2.4` being created)
        type: string
        required: true

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@b62528385c34dbc9f38e5f4225ac829252d1ea92
        with:
          app_id: ${{ secrets.GRAFANA_DELIVERY_BOT_APP_ID }}
          private_key: ${{ secrets.GRAFANA_DELIVERY_BOT_APP_PEM }}
      - name: Bump release branch
        uses: grafana/grafana-github-actions-go/bump-release@main
        with:
          token: ${{ steps.generate_token.outputs.token }}
          ownerRepo: 'grafana/grafana'
          source: ${{ inputs.source }}
