name: Documentation CI
on:
  pull_request:
    paths: ["docs/sources/**"]
  workflow_dispatch:
jobs:
  vale:
    runs-on: ubuntu-latest
    container:
      image: grafana/vale:latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - uses: grafana/writers-toolkit/vale-action@c21c67bc79ebe44a30321d501a21eaf1b9885805 # vale-action/v1.0.0
        with:
          filter: '.Name in ["Grafana.WordList", "Grafana.Spelling", "Grafana.ProductPossessives"]'
          token: ${{ secrets.GITHUB_TOKEN }}
