name: Documentation CI
on:
  pull_request:
    paths: ["docs/sources/**"]
  workflow_dispatch:
jobs:
  vale:
    runs-on: ubuntu-latest
    container:
      image: grafana/vale:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run Vale spellcheck
        run: |
          (cd /etc/vale && vale sync)
          vale --filter '.Name == "Grafana.WordList"' --output=/etc/vale/rdjsonl.tmpl docs/sources | \
            /bin/reviewdog \
              --conf /etc/vale/.reviewdog.yml \
              --fail-on-error \
              --f=rdjsonl \
              --name=vale \
              --reporter github-pr-review
          vale --filter '.Name == "Grafana.Spelling"' --output=/etc/vale/rdjsonl.tmpl docs/sources | \
            /bin/reviewdog \
              --conf /etc/vale/.reviewdog.yml \
              --fail-on-error \
              --f=rdjsonl \
              --name=vale \
              --reporter github-pr-review
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
