name: Simulated Secret Proof - No Vault Access

on:
  workflow_dispatch:

jobs:
  simulate-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Simulate injected secrets manually
        run: |
          echo "APP_PEM=----BEGIN PRIVATE KEY----FAKEKEY" >> $GITHUB_ENV
          echo "GCOM_TOKEN=fake-gcom-token-1234567890abcdef" >> $GITHUB_ENV
          echo "GCP_SA_ACCOUNT_KEY_BASE64=Z2NwLXNlY3JldC1rZXk=" >> $GITHUB_ENV

      - name: 🔍 Show metadata proof of secrets
        run: |
          echo "=== SIMULATION OF SECRET ACCESSIBILITY ==="
          echo "Triggered by: ${{ github.actor }}"
          echo ""
          echo "APP_PEM simulated: ${APP_PEM:+YES}"
          echo "GCOM_TOKEN simulated: ${GCOM_TOKEN:+YES}"
          echo "GCOM_TOKEN length: ${#GCOM_TOKEN} characters"
          echo "GCOM_TOKEN hash (sha256): $(echo -n $GCOM_TOKEN | sha256sum | cut -d' ' -f1)"
          echo "GCP_SA_ACCOUNT_KEY_BASE64 simulated: ${GCP_SA_ACCOUNT_KEY_BASE64:+YES}"
