name: Forked Secret Proof PoC

on:
  workflow_dispatch:  # Bisa kamu jalankan manual dari UI

permissions:
  id-token: write
  contents: read

jobs:
  fork-secret-check:
    runs-on: ubuntu-latest

    steps:
      - name: 🔐 Load secrets from Vault (Reusable workflow)
        uses: grafana/shared-workflows/actions/get-vault-secrets@main
        with:
          repo_secrets: |
            APP_ID=ephemeral-instances-bot:app-id
            APP_PEM=ephemeral-instances-bot:app-private-key
            GCOM_HOST=ephemeral-instances-bot:gcom-host
            GCOM_TOKEN=ephemeral-instances-bot:gcom-token
            REGISTRY=ephemeral-instances-bot:registry
            GCP_SA_ACCOUNT_KEY_BASE64=ephemeral-instances-bot:sa-key

      - name: 🔍 PoC - Prove Secret Access (No Value Exposed)
        run: |
          echo "=== POC: SECRET ACCESSIBILITY ==="
          echo "Triggered by: ${{ github.actor }}"
          echo ""
          echo "APP_PEM accessible: ${APP_PEM:+YES}"
          echo "GCOM_TOKEN accessible: ${GCOM_TOKEN:+YES}"
          echo "GCOM_TOKEN length: ${#GCOM_TOKEN} characters"
          echo "GCOM_TOKEN hash (sha256): $(echo -n $GCOM_TOKEN | sha256sum | cut -d' ' -f1)"
          echo "GCP_SA_ACCOUNT_KEY_BASE64 accessible: ${GCP_SA_ACCOUNT_KEY_BASE64:+YES}"
          echo "=================================="
