name: Crowdin Create Tasks

on:
  workflow_dispatch:
  # TODO uncomment when we're confident this works
  # once a week on Sunday at midnight
  # schedule:
  #   - cron: "0 0 * * 0"

jobs:
  create-tasks-in-crowdin:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'

      - run: yarn install --immutable --check-cache

      - name: Create tasks
        env:
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
        run: node ./.github/workflows/scripts/crowdin/create-tasks.js
