name: Backend Unit Tests - Grafana

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - '**/*.md'
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '**/*.md'

permissions:
  contents: read
  id-token: write

jobs:
  call-backend-unit-tests:
    # Run this workflow only for PRs from forks; if it gets merged into `main`, 
    # the `pr-backend-unit-tests-enterprise` workflow will run instead
    if: github.event_name == 'pull_request' && github.event.pull_request.head.repo.fork == true
    uses: ./.github/workflows/backend-unit-tests.yml
    with:
      wire-tags: 'oss'
    secrets:
      codecov-token: ${{ secrets.CODECOV_TOKEN }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
