name: Backend Unit Tests - Grafana + Enterprise

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - '**/*.md'
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '**/*.md'

permissions:
  contents: read
  id-token: write

jobs:
  call-backend-tests:
    uses: ./.github/workflows/pr-backend-unit-tests-reusable.yml
    with:
      wire-tags: 'enterprise'
    secrets:
      codecov-token: ${{ secrets.CODECOV_TOKEN }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
