name: Backend Unit Tests - Grafana + Enterprise

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - '**/*.md'
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '**/*.md'

permissions:
  contents: read
  id-token: write

jobs:
  call-backend-unit-tests:
    # Run this workflow for non-PR events (like pushes to `main`) OR for internal PRs (PRs not from forks)
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.fork == false
    uses: ./.github/workflows/backend-unit-tests.yml
    with:
      wire-tags: 'enterprise'
    secrets:
      codecov-token: ${{ secrets.CODECOV_TOKEN }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
