name: Backend Unit Tests

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - '**/*.md'
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '**/*.md'

permissions:
  contents: read
  id-token: write

env:
  EDITION: 'oss'
  WIRE_TAGS: 'oss'

jobs:
  check-coverage:
    name: Check Coverage Requirements
    runs-on: ubuntu-latest
    outputs:
      generate: ${{ steps.check-coverage.outputs.generate }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check if coverage should be generated
        id: check-coverage
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          echo "Event: ${{ github.event_name }}"
          echo "Ref: ${{ github.ref }}"
          
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            echo "PR changed files:"
            files=$(gh api repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/files --jq '.[].filename')
            echo "$files"
            if echo "$files" | grep -E "(pkg/|go\.|\.github/workflows/pr-test-backend\.yml)"; then
              echo "Coverage will be generated: true (PR changes)"
              echo "generate=true" >> $GITHUB_OUTPUT
            else
              echo "Coverage will be generated: false"
              echo "generate=false" >> $GITHUB_OUTPUT
            fi
          elif [[ "${{ github.event_name }}" == "push" && "${{ github.ref }}" == "refs/heads/main" ]] && \
               [[ "${{ github.event.head_commit.modified }}" =~ (pkg/|go\.|\.github/workflows/pr-test-backend\.yml) ]]; then
            echo "Coverage will be generated: true (push to main)"
            echo "generate=true" >> $GITHUB_OUTPUT
          else
            echo "Coverage will be generated: false"
            echo "generate=false" >> $GITHUB_OUTPUT
          fi

  backend-tests:
    name: Backend Tests
    needs: [check-coverage]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true
          
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential shared-mime-info

      - name: Verify code generation
        run: |
          CODEGEN_VERIFY=1 make gen-cue
          CODEGEN_VERIFY=1 make gen-jsonnet

      - name: Generate Go code
        run: make gen-go

      - name: Run unit tests
        shell: bash
        run: |
          if [ "${{ needs.check-coverage.outputs.generate }}" == "true" ]; then
            COVER_OPTS="-coverprofile=unit.cov -coverpkg=github.com/grafana/grafana/..." make test-go-unit
          else
            make test-go-unit
          fi

      - name: Upload unit coverage
        if: needs.check-coverage.outputs.generate == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: unit-coverage
          path: unit.cov
          retention-days: 1

  report-coverage:
    name: Generate Coverage Report
    needs: [check-coverage, backend-tests]
    if: needs.check-coverage.outputs.generate == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true

      - name: Generate Go code
        run: make gen-go

      - name: Download unit coverage
        uses: actions/download-artifact@v4
        with:
          name: unit-coverage

      - name: Generate Coverage Report
        uses: ./.github/actions/report-coverage
        with:
          unit-cov-path: unit.cov
      
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
