name: End-to-end tests

on:
  pull_request:
  push:
    branches:
      - main
      - release-*.*.*

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-grafana:
    name: Build & Package Grafana
    runs-on: ubuntu-latest-16-cores
    outputs:
      artifact: ${{ steps.artifact.outputs.artifact }}
    steps:
      - run: touch grafana.tar.gz
      - run: echo "artifact=grafana-e2e-${{github.run_number}}" >> "$GITHUB_OUTPUT"
        id: artifact
      - uses: actions/upload-artifact@v4
        id: upload
        with:
          retention-days: 1
          name: ${{ steps.artifact.outputs.artifact }}
          path: grafana.tar.gz
  misc-suite:
    needs:
      - build-grafana
    uses: ./.github/workflows/e2e-suite-various.yml
    name: Various Suite
    with:
      package: ${{ needs.build-grafana.outputs.artifact }}
