name: "Go Workspace Check"

on:
  workflow_dispatch:
  pull_request:
    branches: [main]
    paths:
      - .github/workflows/pr-go-workspace-check.yml
      - go.mod
      - go.sum
      - go.work
      - go.work.sum
      - '**/go.mod'
      - '**/go.sum'
      - '**.go'

jobs:
  check:
    name: Go Workspace Check
    runs-on: ubuntu-latest
    permissions:
      contents: read # clone the repository
      id-token: write # required for Vault access

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        persist-credentials: false

    - name: Set go version
      uses: actions/setup-go@19bb51245e9c80abacb2e91cc42b33fa478b8639
      with:
        cache: false
        go-version-file: go.mod

    - name: Setup Grafana Enterprise
      if: github.event.pull_request.head.repo.fork == false
      uses: ./.github/actions/setup-enterprise
      with:
        github-app-name: 'grafana-ci-bot'

    - name: Update workspace
      run: make update-workspace

    - name: Check for go mod & workspace changes 
      run: |
        if ! git diff --exit-code --quiet; then
          echo "Changes detected:"
          git diff
          echo "Please run 'make update-workspace' and commit the changes."
          echo "If there are wire changes, please link Enterprise before running the command."
          echo "If there is a change in enterprise dependencies, please update pkg/extensions/main.go."
          exit 1
        fi
    - name: Ensure Dockerfile contains submodule COPY commands
      run: ./scripts/go-workspace/validate-dockerfile.sh
