name: Documentation

on:
  pull_request:
    paths:
      - '*.md'
      - 'docs/**'
      - 'packages/**/*.md'
      - 'latest.json'
      - '.github/workflows/pr-lint-build-docs.yml'

jobs:
  docs:
    name: Build & Verify Docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.11.0'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --immutable

      - name: Lint docs
        run: yarn run prettier:checkDocs
        env:
          # Increase memory for prettier due to large number of files
          NODE_OPTIONS: --max_old_space_size=8192

      - name: Build docs website
        run: |
          # Create a temporary directory for Hugo content
          mkdir -p /tmp/hugo/content/docs/grafana/latest
          
          cat << EOF > /tmp/hugo/content/docs/grafana/_index.md
          ---
          redirectURL: /docs/grafana/latest/
          type: redirect
          versioned: true
          ---
          EOF
          
          # Copy docs sources to the temporary Hugo directory
          cp -r docs/sources/* /tmp/hugo/content/docs/grafana/latest/
          
          # Run Hugo directly to build the site
          docker run --rm -v /tmp/hugo:/hugo grafana/docs-base:latest /bin/sh -c "cd /hugo && hugo build"
      
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true

      - name: Verify generated CUE code
        run: CODEGEN_VERIFY=1 make gen-cue
