name: Test Backend

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - '**/*.md'
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '**/*.md'

permissions:
  contents: read
  id-token: write

env:
  GO_VERSION: '1.23.5'
  EDITION: 'oss'
  WIRE_TAGS: 'oss'

jobs:
  check-coverage:
    name: Check Coverage Requirements
    runs-on: ubuntu-latest
    outputs:
      generate: ${{ steps.check-coverage.outputs.generate }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check if coverage should be generated
        id: check-coverage
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          echo "Event: ${{ github.event_name }}"
          echo "Ref: ${{ github.ref }}"
          
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            echo "PR changed files:"
            files=$(gh api repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/files --jq '.[].filename')
            echo "$files"
            if echo "$files" | grep -E "(pkg/|go\.|\.github/workflows/pr-test-backend\.yml)"; then
              echo "Coverage will be generated: true (PR changes)"
              echo "generate=true" >> $GITHUB_OUTPUT
            else
              echo "Coverage will be generated: false"
              echo "generate=false" >> $GITHUB_OUTPUT
            fi
          elif [[ "${{ github.event_name }}" == "push" && "${{ github.ref }}" == "refs/heads/main" ]] && \
               [[ "${{ github.event.head_commit.modified }}" =~ (pkg/|go\.|\.github/workflows/pr-test-backend\.yml) ]]; then
            echo "Coverage will be generated: true (push to main)"
            echo "generate=true" >> $GITHUB_OUTPUT
          else
            echo "Coverage will be generated: false"
            echo "generate=false" >> $GITHUB_OUTPUT
          fi

  verify-code-generation:
    name: Verify Code Generation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true
          
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential shared-mime-info

      - name: Verify CUE generation
        run: CODEGEN_VERIFY=1 make gen-cue

      - name: Verify Jsonnet generation
        run: CODEGEN_VERIFY=1 make gen-jsonnet

  run-tests:
    strategy:
      matrix:
        test-type: [unit, integration]
    name: ${{ matrix.test-type == 'unit' && 'Unit Tests' || 'Integration Tests' }}
    needs: [check-coverage, verify-code-generation]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true

      - name: Run ${{ matrix.test-type }} tests
        shell: bash
        run: |
          if [ "${{ needs.check-coverage.outputs.generate }}" == "true" ]; then
            COVER_OPTS="-coverprofile=${{ matrix.test-type }}.cov -coverpkg=github.com/grafana/grafana/..." make gen-go test-go-${{ matrix.test-type }}
          else
            make gen-go test-go-${{ matrix.test-type }}
          fi

      - name: Upload ${{ matrix.test-type }} coverage
        if: needs.check-coverage.outputs.generate == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.test-type }}-coverage
          path: ${{ matrix.test-type }}.cov
          retention-days: 1

  report-coverage:
    name: Generate Coverage Report
    needs: [check-coverage, run-tests]
    if: needs.check-coverage.outputs.generate == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true

      - name: Generate Go code
        run: make gen-go

      - name: Download unit coverage
        uses: actions/download-artifact@v4
        with:
          name: unit-coverage

      - name: Download integration coverage
        uses: actions/download-artifact@v4
        with:
          name: integration-coverage

      - name: Generate Coverage Report
        uses: ./.github/actions/report-coverage
        with:
          unit-cov-path: unit.cov
          integration-cov-path: integration.cov

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
