name: Test Backend

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - '**/*.md'
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '**/*.md'

permissions:
  contents: read
  id-token: write

env:
  EDITION: 'oss'

jobs:
  check-coverage:
    name: Check Coverage Requirements
    runs-on: ubuntu-latest
    outputs:
      generate: ${{ steps.check-coverage.outputs.generate }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check if coverage should be generated
        id: check-coverage
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          echo "Event: ${{ github.event_name }}"
          echo "Ref: ${{ github.ref }}"
          
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            echo "PR changed files:"
            files=$(gh api repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/files --jq '.[].filename')
            echo "$files"
            if echo "$files" | grep -E "(pkg/|go\.)"; then
              echo "Coverage will be generated: true (PR changes)"
              echo "generate=true" >> $GITHUB_OUTPUT
            else
              echo "Coverage will be generated: false"
              echo "generate=false" >> $GITHUB_OUTPUT
            fi
          elif [[ "${{ github.event_name }}" == "push" && "${{ github.ref }}" == "refs/heads/main" ]] && \
               [[ "${{ github.event.head_commit.modified }}" =~ (pkg/|go\.|\.github/workflows/pr-test-backend\.yml) ]]; then
            echo "Coverage will be generated: true (push to main)"
            echo "generate=true" >> $GITHUB_OUTPUT
          else
            echo "Coverage will be generated: false"
            echo "generate=false" >> $GITHUB_OUTPUT
          fi

  setup-enterprise:
    name: Setup Enterprise
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.pull_request.head.repo.fork == false
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Enterprise
        uses: ./.github/actions/setup-enterprise

      - name: Package Enterprise Code
        shell: bash
        run: |
          cd ..
          tar -czf $GITHUB_WORKSPACE/enterprise.tar.gz grafana-enterprise/

      - name: Upload Enterprise Code
        uses: actions/upload-artifact@v4
        with:
          name: enterprise-code
          path: enterprise.tar.gz
          # We don't need to keep the enterprise code around for more than the duration of the workflow
          retention-days: 0

  setup:
    name: Setup Environment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.5'
          cache: true
          
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential shared-mime-info make

      - name: Verify CUE generation
        run: CODEGEN_VERIFY=1 make gen-cue

      - name: Verify Jsonnet generation
        run: CODEGEN_VERIFY=1 make gen-jsonnet

  unit-tests:
    name: Unit Tests
    needs: [check-coverage, setup, setup-enterprise]
    runs-on: ubuntu-latest
    env:
      EDITION: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.repo.fork == false && 'enterprise' || 'oss' }}
      WIRE_TAGS: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.repo.fork == false && 'enterprise' || 'oss' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.5'
          cache: true

      - name: Download Enterprise Code
        if: github.event_name == 'pull_request' && github.event.pull_request.head.repo.fork == false
        uses: actions/download-artifact@v4
        with:
          name: enterprise-code
          path: ..

      - name: Extract Enterprise Code
        if: github.event_name == 'pull_request' && github.event.pull_request.head.repo.fork == false
        shell: bash
        run: |
          cd ..
          tar -xzf enterprise.tar.gz

      - name: Run unit tests
        uses: ./.github/actions/run-backend-tests
        with:
          coverage-opts: ${{ needs.check-coverage.outputs.generate == 'true' && '-coverprofile=unit.cov -coverpkg=github.com/grafana/grafana/...' || '' }}
          test-command: 'make gen-go test-go-unit'

      - name: Upload unit coverage
        if: needs.check-coverage.outputs.generate == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: unit-coverage
          path: unit.cov
          retention-days: 30

  integration-tests:
    name: Integration Tests
    needs: [check-coverage, setup, setup-enterprise]
    runs-on: ubuntu-latest
    env:
      EDITION: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.repo.fork == false && 'enterprise' || 'oss' }}
      WIRE_TAGS: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.repo.fork == false && 'enterprise' || 'oss' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.5'
          cache: true

      - name: Download Enterprise Code
        if: github.event_name == 'pull_request' && github.event.pull_request.head.repo.fork == false
        uses: actions/download-artifact@v4
        with:
          name: enterprise-code
          path: ..

      - name: Extract Enterprise Code
        if: github.event_name == 'pull_request' && github.event.pull_request.head.repo.fork == false
        shell: bash
        run: |
          cd ..
          tar -xzf enterprise.tar.gz

      - name: Run integration tests
        uses: ./.github/actions/run-backend-tests
        with:
          coverage-opts: ${{ needs.check-coverage.outputs.generate == 'true' && '-coverprofile=integration.cov -coverpkg=github.com/grafana/grafana/...' || '' }}
          test-command: 'make gen-go test-go-integration'

      - name: Upload integration coverage
        if: needs.check-coverage.outputs.generate == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: integration-coverage
          path: integration.cov
          retention-days: 30

  report-coverage:
    name: Generate Coverage Report
    needs: [check-coverage, unit-tests, integration-tests]
    if: needs.check-coverage.outputs.generate == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download unit coverage
        uses: actions/download-artifact@v4
        with:
          name: unit-coverage

      - name: Download integration coverage
        uses: actions/download-artifact@v4
        with:
          name: integration-coverage

      - name: Generate Coverage Report
        uses: ./.github/actions/report-coverage
        with:
          unit-cov-path: unit.cov
          integration-cov-path: integration.cov

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
