name: Test Backend

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - '**/*.md'
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '**/*.md'

permissions:
  contents: read
  id-token: write

env:
  EDITION: 'oss'

jobs:
  test-backend:
    name: Test Backend
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.5'
          cache: true
          
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential shared-mime-info make

      - name: Get runner name
        run: echo ${{ runner.name }}

      # - name: Setup Enterprise (PR only)
      #   if: github.event_name == 'pull_request' && github.event.pull_request.head.repo.fork == false
      #   uses: ./.github/workflows/actions/setup-enterprise
        # Optionally enable debug output with:
        # with:
        #   debug: 'true'

      - name: Verify CUE generation
        run: CODEGEN_VERIFY=1 make gen-cue

      - name: Verify Jsonnet generation
        run: CODEGEN_VERIFY=1 make gen-jsonnet

      - name: Wire install
        run: make gen-go

      - name: Run backend tests
        uses: ./.github/workflows/actions/run-backend-tests
        # Optionally configure with:
        # with:
        #   timeout: '10m'
        #   short: 'false'

      - name: Run backend integration tests
        uses: ./.github/workflows/actions/run-backend-integration-tests
        # Optionally configure with:
        # with:
        #   timeout: '10m'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
