name: Test Backend

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - '**/*.md'
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '**/*.md'

permissions:
  contents: read
  id-token: write

env:
  EDITION: 'oss'

jobs:
  test-backend:
    name: Test Backend
    runs-on: ubuntu-latest
    continue-on-error: true
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.5'
          cache: true
          
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential shared-mime-info make

      - name: Get runner name
        run: echo ${{ runner.name }}

      - name: Setup Enterprise (PR only)
        if: github.event_name == 'pull_request' && github.event.pull_request.head.repo.fork == false
        uses: ./.github/actions/setup-enterprise

      - name: Verify CUE generation
        run: CODEGEN_VERIFY=1 make gen-cue

      - name: Verify Jsonnet generation
        run: CODEGEN_VERIFY=1 make gen-jsonnet

      - name: Check if coverage should be generated
        id: check-coverage
        run: |
          if [[ "${{ github.event_name }}" == "push" && "${{ github.ref }}" == "refs/heads/main" ]] && \
             [[ "${{ github.event.head_commit.modified }}" =~ (pkg/|go\.|\.github/workflows/pr-test-backend\.yml) ]]; then
            echo "generate=true" >> $GITHUB_OUTPUT
          else
            echo "generate=false" >> $GITHUB_OUTPUT
          fi

      - name: Run backend tests
        uses: ./.github/actions/run-backend-tests
        with:
          generate-coverage: ${{ steps.check-coverage.outputs.generate }}

      - name: Run backend integration tests
        uses: ./.github/actions/run-backend-integration-tests
        with:
          generate-coverage: ${{ steps.check-coverage.outputs.generate }}

      - name: Generate Coverage Report
        if: steps.check-coverage.outputs.generate == 'true'
        uses: ./.github/actions/report-coverage
        with:
          unit-cov-path: unit.cov
          integration-cov-path: integration.cov

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
