name: Run dashboard schema v2 e2e

on:
  # schedule:
  #   - cron: '0 8 * * 1-5' # every day at 08:00UTC on weekdays
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**' 

env:
  ARCH: linux-amd64

jobs:
  dashboard-schema-v2-e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Pin Go version to mod file
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - run: go version
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install --immutable
      - name: Build grafana
        run: make build
      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          start: yarn e2e:schema-v2